### PR TITLE
Workflow details

### PR DESCRIPTION
**Pull request by rubenperezm**
Workflow details tab

- [x] Workflow overview with a refresh button
- [x] Workflow engine logs
- [x] Workflow job logs, with a dropdown menu to display the logs of a specific step
- [x] Workspace  
- [x] Workflow Specification

### CODE REVIEW

**Comment by rubenperezm** [comment]
Could you please test the refresh button on your computers? I'm still working on the refresh action, but it seems that the starting date of the workflow (given by Reana Server) is later than the current time on my computer (approximately -20 seconds): 
image

In Reana-UI the difference seems to be +40 seconds (this is the workflow right after changing its status to running): 
image

**Comment by Soap2G** [comment]
Just a couple of comments: 
### 1. base pwd
When spawning a terminal, the WORKDIR is:
```sh
(base) jovyan@d696a79860eb:/reana-jupyterlab-extension$ pwd
/reana-jupyterlab-extension
```
While it should be `/home/jovyan`. Can we fix that? 

### 2. reana-client
Also, can we install `reana-client` in the docker image? So that users don't have to `pip install` it every time.

**Comment by rubenperezm** [comment]
PR is ready for review now. When merged, should close #8.

**Review by Soap2G — APPROVED** [review]
lgtm.
Closes #8

**Review by garciagenrique — APPROVED** [review]
thanks @rubenperezm you can merge and create the new PR with the create-tab devs!

**Pull request merged**
